# Generated by Django 5.0.1 on 2024-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen_uno', models.ImageField(upload_to='img1')),
                ('imagen_dos', models.ImageField(upload_to='img2')),
                ('nombre_vendedor', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
