# Generated by Django 4.2 on 2024-04-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_dos',
        ),
    ]
